version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.maps.android:android-maps-utils
    versions:
    - 2.2.0
    - 2.2.1
    - 2.2.2
  - dependency-name: com.google.firebase:firebase-auth
    versions:
    - 20.0.2
    - 20.0.3
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: com.google.firebase:firebase-database
    versions:
    - 19.6.0
  - dependency-name: junit:junit
    versions:
    - 4.13.1
